web:
# port: 3000 # The port the webserver listens to

# The root path for the folder containing the modules (each in their own folder)
modules_path: ../modules

log:
  level: info
  # included_modules:
  #  - growatt-3ph-mod-tl3-x
  # excluded_modules:
  #  - MqttManager

mqtt:
  host: mosquitto.local.x256.nl # The host of your MQTT broker
# port: 1883 # The port your MQTT broker is listening on
# username: # The username to authenticate with
# password: # The password to authenticate with
# protocol: mqtt # The protocol to use for MQTT, can be mqtt or ws
# validate_certificate: true # Whether to validate the certificate of the MQTT broker
# base_topic: quantumhub # The base topic to use for MQTT

modules:
  - package: modbus-solarman
    identifier: quantumhub_growatt_3ph_mod_tl3_x
    name: Growatt 3PH MOD TL3-X series
    device: growatt-tl3
    host: 10.210.5.12
    port: 502
    unitId: 1
    updateInterval: 5
    solarman: false
    # serial: 123456789 # This is needed when you are connecting through solarman

  - package: modbus-solarman
    identifier: quantumhub_afore_af_xk_th
    name: Afore AF XK-TH Inverter
    device: af-xk-th-three-phase-hybrid
    host: 10.210.5.19
    port: 8899
    unitId: 1
    updateInterval: 5
    solarman: false
    serial: 3518024876 # This is needed when you are connecting through solarman

  - package: internal-test
    identifier: quantumhub_new_york_clock
    name: New York Clock
    timezone: America/New_York
  - package: internal-test
    identifier: quantumhub_amsterdam_clock
    name: Amsterdam Clock
    timezone: Europe/Amsterdam

homeassistant:
# availability: true # Whether to publish availability messages
# base_topic: homeassistant # The base topic to use for Home Assistant discovery
