web:
# port: 3000 # The port the webserver listens to

instance_name: qt

log:
  level: info
  # included_modules:
  #  - quantumhub_afore_af_xk_th
  # excluded_modules:
  #  - MqttManager

mqtt:
  host: mosquitto.local.x256.nl # The host of your MQTT broker
# port: 1883 # The port your MQTT broker is listening on
# username: # The username to authenticate with
# password: # The password to authenticate with
# protocol: mqtt # The protocol to use for MQTT, can be mqtt or ws
# validate_certificate: true # Whether to validate the certificate of the MQTT broker
  base_topic: qt # The base topic to use for MQTT

storage:
  file: 'storage.sqlite'

packages:
  root: ./packages
  configuration:
    - package: example-device
      identifier: new_york_clock
      name: New York Clock
      timezone: America/New_York
    - package: example-device
      identifier: amsterdam_clock
      name: Amsterdam Clock
      timezone: Europe/Amsterdam
    - package: example-climate
      identifier: heater
      name: Heater
    - package: growatt
      identifier: quantumhub_growatt_3ph_mod_tl3_x
      name: Growatt 3PH MOD TL3-X series
      device: growatt-tl3
      host: 10.210.5.12
      port: 502
      unitId: 1
      updateInterval: 1
      solarman: false
      config_file: /Volumes/Projects/quantumhub/modules/modbus-solarman/growatt.yaml
      disabled: false
      unavailable_timeout: 180 # When no successful read is done, the device is marked as unavailable after this timeout (Seconds)
      # serial: 123456789 # This is needed when you are connecting through solarman      

homeassistant:
# availability: true # Whether to publish availability messages
# base_topic: homeassistant # The base topic to use for Home Assistant discovery
