web:
# port: 3000 # The port the webserver listens to

# The root path for the folder containing the packages (each in their own folder)
instance_name: quantumhub

log:
  level: info
  # included_modules:
  #  - quantumhub_afore_af_xk_th
  # excluded_modules:
  #  - MqttManager

mqtt:
  host: mosquitto.local.x256.nl # The host of your MQTT broker
# port: 1883 # The port your MQTT broker is listening on
# username: # The username to authenticate with
# password: # The password to authenticate with
# protocol: mqtt # The protocol to use for MQTT, can be mqtt or ws
# validate_certificate: true # Whether to validate the certificate of the MQTT broker
# base_topic: quantumhub # The base topic to use for MQTT

packages:
  root: ./packages
  configuration:
    - package: example-device
      identifier: quantumhub_new_york_clock
      name: New York Clock
      timezone: America/New_York
    - package: example-climate
      identifier: quantumhub_amsterdam_clock
      name: Amsterdam Clock
      timezone: Europe/Amsterdam
    - package: example-climate
      identifier: quantumhub_heater
      name: Heater
homeassistant:
# availability: true # Whether to publish availability messages
# base_topic: homeassistant # The base topic to use for Home Assistant discovery
