export enum ProcessStatus {
  LOADED = 'LOADED',
  INITIALIZED = 'INITIALIZED',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  DESTROYED = 'DESTROYED',
}
